export enum FormCategory {
  GESTION_DIRECCION = 'GESTION_DIRECCION',
  GESTION_INTEGRAL = 'GESTION_INTEGRAL',
  GESTION_COMERCIAL = 'GESTION_COMERCIAL',
  GESTION_COMPRAS = 'GESTION_COMPRAS',
  OPERACION_LOGISTICA = 'OPERACION_LOGISTICA',
  MANTENIMIENTO = 'MANTENIMIENTO',
  GESTION_FINANCIERA = 'GESTION_FINANCIERA',
  GESTION_HUMANA = 'GESTION_HUMANA',
  PREPARADOS_ESTERILES = 'PREPARADOS_ESTERILES',
  DISTRIBUCION_MEDICAMENTOS = 'DISTRIBUCION_MEDICAMENTOS',
}